var annotated_dup =
[
    [ "Analog", "struct_analog.html", "struct_analog" ],
    [ "angle_struct", "structangle__struct.html", "structangle__struct" ],
    [ "avg_struct_10", "structavg__struct__10.html", "structavg__struct__10" ],
    [ "CANMessageInfo", "struct_c_a_n_message_info.html", "struct_c_a_n_message_info" ],
    [ "clarke3F_struct", "structclarke3_f__struct.html", "structclarke3_f__struct" ],
    [ "datalog_struct", "structdatalog__struct.html", "structdatalog__struct" ],
    [ "Duties", "struct_duties.html", "struct_duties" ],
    [ "Encoder", "struct_encoder.html", "struct_encoder" ],
    [ "Feedback", "struct_feedback.html", "struct_feedback" ],
    [ "filtreLP_struct", "structfiltre_l_p__struct.html", "structfiltre_l_p__struct" ],
    [ "iclarke3F_struct", "structiclarke3_f__struct.html", "structiclarke3_f__struct" ],
    [ "InverterStruct", "struct_inverter_struct.html", "struct_inverter_struct" ],
    [ "irot_struct", "structirot__struct.html", "structirot__struct" ],
    [ "LED", "struct_l_e_d.html", "struct_l_e_d" ],
    [ "MotorParameters", "struct_motor_parameters.html", "struct_motor_parameters" ],
    [ "pi_aw_struct", "structpi__aw__struct.html", "structpi__aw__struct" ],
    [ "pi_struct", "structpi__struct.html", "structpi__struct" ],
    [ "rampa_dual_struct", "structrampa__dual__struct.html", "structrampa__dual__struct" ],
    [ "rampa_struct", "structrampa__struct.html", "structrampa__struct" ],
    [ "Reference", "struct_reference.html", "struct_reference" ],
    [ "RMS_struct", "struct_r_m_s__struct.html", "struct_r_m_s__struct" ],
    [ "rot_struct", "structrot__struct.html", "structrot__struct" ],
    [ "signal", "structsignal.html", "structsignal" ],
    [ "signal_positioned", "structsignal__positioned.html", "structsignal__positioned" ],
    [ "step_struct", "structstep__struct.html", "structstep__struct" ],
    [ "svpwm_struct", "structsvpwm__struct.html", "structsvpwm__struct" ]
];